import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import { Search } from "@/components/Search/Search";
import { Footer } from "@/components/Footer/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.page}>
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/google_logo.png"
            alt="Google logo"
            width={272}
            height={92}
            priority
          />

          <Search />
        </main>
        <Footer />
      </div>
    </>
  );
}
