import { useSearchParams } from "next/navigation";
import Head from "next/head";
import { Header } from "@/components/Header/Header";
import { ResultList } from "@/components/ResultsList/ResultsList";
import { PaginationControl } from "@/components/PaginationControls/PaginationControls";
import { useFetchData } from "@/hooks/useFetchData";
import { usePagination } from "@/hooks/usePagination";
import { Footer } from "@/components/Footer/Footer";

export default function SearchResults() {
  const searchParams = useSearchParams();
  const searchQuery = searchParams.get("q") || undefined;

  const { results, isLoading, error, animalTypes } = useFetchData(searchQuery);
  const {
    currentPage,
    paginatedResults,
    handleNextPage,
    handlePrevPage,
    disableNextButton,
    disablePrevButton,
  } = usePagination(results, 10);

  return (
    <>
      <Head>
        <title>{searchQuery} - Search with Google</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header searchQuery={searchQuery} />
      <main>
        <ResultList
          results={paginatedResults}
          isLoading={isLoading}
          searchQuery={searchQuery}
          error={error}
          animalTypes={animalTypes}
        />
        <PaginationControl
          currentPage={currentPage}
          handleNextPage={handleNextPage}
          handlePrevPage={handlePrevPage}
          disableNextButton={disableNextButton}
          disablePrevButton={disablePrevButton}
        />
      </main>
      <Footer />
    </>
  );
}
